### ISSUE TITLE
OSError: cannot open recourse

### ISSUE THREAD

**Issue by jsfs11** [hako-mikan/sd-webui-lora-block-weight#100]
Windows 11, Auto1111 1.5.1. Seems to be the same error as #66 reported.

Roboto-Regular is in the scripts folder as well as installed to Windows.

      Traceback (most recent call last):
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 649, in get_font
        return ImageFont.truetype(opts.font or fontpath, fontsize)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
        return freetype(font)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
        self.font = core.getfont(
    OSError: cannot open resource

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "M:\stable-diffusion-webui\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "M:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "M:\stable-diffusion-webui\modules\txt2img.py", line 59, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 686, in newrun
        processed = script.run(p, *script_args)
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 474, in run
        grids.append(smakegrid(images,xst,yst,origin,p))
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 639, in smakegrid
        grid = draw_origin(grid, currentmodel,w*len(xs),h*len(ys),w)
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 660, in draw_origin
        fnt = get_font(fontsize)
      File "M:\stable-diffusion-webui\scripts\lora_block_weight.py", line 651, in get_font
        return ImageFont.truetype(fontpath, fontsize)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
        return freetype(font)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
        return FreeTypeFont(font, size, index, encoding, layout_engine)
      File "M:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
        self.font = core.getfont(
    OSError: cannot open resource

**Comment by hako-mikan** [comment]
May be fixed.
