### ISSUE TITLE
How to use Elemental in AUTOMATIC1111 1.5.1 

### ISSUE THREAD

**Issue by eebp** [hako-mikan/sd-webui-lora-block-weight#104]
I want to know how to use Lora Elemental in prompt.
I tried this 
<lora:randoseru_v1.3:1.0:1.0:lbwe=ATTNDEEPON>

I'd get the error like this
*** Error running after_extra_networks_activate: C:\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "C:\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 535, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "C:\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 324, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "C:\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 579, in loradealer
        elements.append(elementals[called.items[3]])
    KeyError: 'lbwe=ATTNDEEPON'

I'm using AUTOMATIC1111 webui 1.5.1 
1111 version is https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/68f336bd994bed5442ad95bad6b6ad5564a5409a
sd-webui-lora-block-weight version is https://github.com/hako-mikan/sd-webui-lora-block-weight/commit/3eba7323d60c12a0c4b4da50f5522d22ce11d02c

**Comment by hako-mikan** [comment]
I thought I had set it up to work with lbwe=, but it seems there was a bug. 
Thanks.
I've fixed it.

**Comment by eebp** [comment]
Thank you!
Note: It looks like I need to specify both lbw and lbwe to work.  Which is OK.

This works for me.
<lora:loraname:1.0:1.0:lbw=ALL:lbwe=PROJDEEPOFF>

This didn't.
<lora:loraname:1.0:1.0:lbwe=PROJDEEPOFF>
