### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Entropy2019** [hako-mikan/sd-webui-lora-block-weight#108]
*** Error running after_extra_networks_activate: A:\Stable-Diffusion\novelai-webui-aki\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "A:\Stable-Diffusion\novelai-webui-aki\modules\scripts.py", line 635, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "A:\Stable-Diffusion\novelai-webui-aki\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 327, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "A:\Stable-Diffusion\novelai-webui-aki\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 557, in loradealer
        multiple = float(syntaxdealer(called.items,"unet=","te=",1))
      File "A:\Stable-Diffusion\novelai-webui-aki\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 596, in syntaxdealer
        return items[index] if "@" not in items[index] else 1
    IndexError: list index out of range
    ---
    I updated the plugin to the latest version in Stable Diffusion Web UI v1.6, but I've noticed that it's not working anymore. I encountered some problems while performing actions, but I'm unsure about the exact cause.

**Comment by Entropy2019** [comment]
I did test
It works fine when I use this
<lora:"lora name":0.7:lbw=1,1,1,1,1,0,0,0,1,1,1,1,1,1,1,0,0>
It gives an error when I use custom abbreviations
<lora:"lora name":0.7:lbw=CHAR>

**Comment by hako-mikan** [comment]
Are you using with other extensions?
