### ISSUE TITLE
Draw grid error

### ISSUE THREAD

**Issue by Darkenlord1** [hako-mikan/sd-webui-lora-block-weight#13]
When trying to do Effective Block Analyzer getting this error:

```
Traceback (most recent call last):
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\GitProjects\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 815, in newrun
    processed = script.run(p, *script_args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 343, in run
    grids.append(smakegrid(images,xs,ys,origin,p))
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 771, in smakegrid
    grid = images.draw_grid_annotations(grid,int(p.width), int(p.height), hor_texts, ver_texts)
  File "D:\GitProjects\stable-diffusion-webui\modules\images.py", line 177, in draw_grid_annotations
    assert cols == len(hor_texts), f'bad number of horizontal texts: {len(hor_texts)}; must be {cols}'
AssertionError: bad number of horizontal texts: 3; must be 6
```

If you need any other info, feel free to ask. Ty.

**Comment by Darkenlord1** [comment]
Thanks, fixed.
