### ISSUE TITLE
Tags are not in list

### ISSUE THREAD

**Issue by Darkenlord1** [hako-mikan/sd-webui-lora-block-weight#14]
When trying to XYZ plot with example values from [fun usage](https://github.com/hako-mikan/sd-webui-lora-block-weight#fun-usage), getting this error:
```
Traceback (most recent call last):
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\GitProjects\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 815, in newrun
    processed = script.run(p, *script_args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 314, in run
    if "values" in xtype:c_base = weightsdealer(x,y,base)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 277, in weightsdealer
    flagger[blockid.index(id)] =changer
ValueError: 'ALL' is not in list
```

I am putting this `NOT,ALL,INS,IND,INALL,MIDD,OUTD,OUTS,OUTALL` in box right from "Active" checkbox and in "Y values"

And putting these:
> NOT:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
> ALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
> INS:1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
> IND:1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0
> INALL:1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0
> MIDD:1,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0
> OUTD:1,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0
> OUTS:1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1
> OUTALL:1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1

into Weights setting and clicking "Save presets"

And if i click on "Reload Tags" it erases anything in box, which is right from "Active" checkbox.

If you need any other info, feel free to ask. Ty.

**Comment by hako-mikan** [comment]
In this case, specify "Original weight" for the Y type. Block ID" is a type that specifies a blocks such as "BASE, IN02".

**Comment by Darkenlord1** [comment]
> In this case, specify "Original weight" for the Y type. Block ID" is a type that specifies a blocks such as "BASE, IN02".
did that, and now getting this error:

```
Traceback (most recent call last):
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\GitProjects\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\GitProjects\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 821, in newrun
    processed = script.run(p, *script_args)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 318, in run
    xyzdealer(y,ytype)
  File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 301, in xyzdealer
    if "Weights" in at:base =c_base = lratios[a]
KeyError: 'NOT'
```

![image](https://user-images.githubusercontent.com/20936024/226381836-757668be-79ae-4e21-aeed-8269ae09c467.png)

**Comment by Darkenlord1** [comment]
understood why, number of weights need to be exact 17, count maybe related to is it lora or locon, not sure.
