### ISSUE TITLE
error after update new version

### ISSUE THREAD

**Issue by Morroli** [hako-mikan/sd-webui-lora-block-weight#141]
code:

*** Error running after_extra_networks_activate: F:\AIGC\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\AIGC\stable-diffusion-webui\modules\scripts.py", line 635, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "F:\AIGC\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 402, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "F:\AIGC\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 694, in loradealer
        te,unet = multidealer(te,unet)
      File "F:\AIGC\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 775, in multidealer
        return float(t),float(u)
    ValueError: could not convert string to float: '1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0'

The extension works well until update new version. never happened before and I report it. 

BTW: I love this extension, and many thinks hako mikan. 
great work.

**Comment by mauzus** [comment]
Use 'lbw=1,1,1,1,1,0,0.2,0,0.8,1,1,0.2,0,0,0,0,0' instead.
