### ISSUE TITLE
Forgeでエラーが発生して動作しないようです。

### ISSUE THREAD

**Issue by zombino999** [hako-mikan/sd-webui-lora-block-weight#167]
```
*** Error running postprocess: xxxxxxxxxxxxxx\webui_forge_cu121_torch21\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "xxxxxxxxxxxxxx\webui_forge_cu121_torch21\webui\modules\scripts.py", line 900, in postprocess
        script.postprocess(p, processed, *script_args)
      File "xxxxxxxxxxxxxx\webui_forge_cu121_torch21\webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 518, in postprocess
        emb_db = sd_hijack.model_hijack.embedding_db
    AttributeError: 'StableDiffusionModelHijack' object has no attribute 'embedding_db'
```

環境は
version: [f2.0.1v1.10.1-previous-450-gdb6448df](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/db6448df744a8929d8ac05d87dec9e85ec8ea48b)  •  python: 3.10.6  •  torch: 2.1.2+cu121
です。

**Comment by diodiogod** [comment]
> I also encountered the same problem as you, but I solved it.
> At first I thought it was a problem with lbw, but then I tested it on sd-webui and it didn't happen, so I suspected it was a problem with the latest version of forge, then I downloaded and used the previous version of forge, lbw worked, and this error no longer occurred.
> I hope it helps you.

You didn't solve it, you just used a previous working version.
On the old Forge you can't use Flux for example.
The new forge is not working with this extension and, I hope I'm wrong, but it's been 4 months since any commit on this project, I wonder if it will ever be updated.

**Comment by LinHeZheng** [comment]
> > I also encountered the same problem as you, but I solved it.
> > At first I thought it was a problem with lbw, but then I tested it on sd-webui and it didn't happen, so I suspected it was a problem with the latest version of forge, then I downloaded and used the previous version of forge, lbw worked, and this error no longer occurred.
> > I hope it helps you.
> 
> You didn't solve it, you just used a previous working version. On the old Forge you can't use Flux for example. The new forge is not working with this extension and, I hope I'm wrong, but it's been 4 months since any commit on this project, I wonder if it will ever be updated.

Yes, you are correct. The problem is that the latest version of forge is not compatible with the current version of lbw.
I think it is because the latest version of forge has changed a lot of things, especially the sd_hijack part required by lbw has been adjusted, which makes the latest version of forge incompatible with lbw.
At present, we can only wait whether the later forge can solve this problem or the lbw author will actively adapt to the latest version of forge.

**Comment by CoqueTornado** [comment]
I think the gradio 4 of the newer forge is not compatible with the extensions of the forge XL age. I think so. Maybe that sd_hijack part or even more. Who knows.

**Comment by diodiogod** [comment]
You guys can try the new fork by @nihedon https://github.com/nihedon/sd-webui-lora-block-weight/
It needs Forge to be on an old commit: 8e4a6fc https://github.com/nihedon/sd-webui-weight-helper/issues/11#issuecomment-2331326726

But it works (for SDXL and SD) with the new forge.

**Comment by hako-mikan** [comment]
Thanks @nihedon.
He fixed it, so please try it on.

**Comment by zombino999** [comment]
@hako-mikan 
エラーの調整ありがとうございます。
通常の生成では問題なく動作することを確認したのですが、高解像度補助を使用するとLoRA自体が適用されていないような出力になってしまうようです。特にコンソール上にエラーは出ていないようなのですが…。
ご検討いただけると幸いです。

**Comment by DDesmondd** [comment]
> Thanks @nihedon. He fixed it, so please try it on.

Same problem as above, lora not loading with Hiresfix on

**Comment by ddoscv** [comment]
@diodiogod Hi, I can't find "8e4a6fc" anywhere from [Panchovix](https://github.com/Panchovix/stable-diffusion-webui-reForge/commits/main/) or [Illyasviel](https://github.com/lllyasviel/stable-diffusion-webui-forge/compare/main...Panchovix:stable-diffusion-webui-reForge:main). Am I looking at the wrong area? I'm using Panchovix's version of [Forge](https://github.com/Panchovix/stable-diffusion-webui-reForge). 

I am having the same issue too. I am already using nihedon's fork but I'm still getting the error message. Sorry I know nothing about this and I'm not even sure if I'm using the right terminologies.

**Comment by diodiogod** [comment]
> @diodiogod Hi, I can't find "8e4a6fc" anywhere from [Panchovix](https://github.com/Panchovix/stable-diffusion-webui-reForge/commits/main/) or [Illyasviel](https://github.com/lllyasviel/stable-diffusion-webui-forge/compare/main...Panchovix:stable-diffusion-webui-reForge:main). Am I looking at the wrong area? I'm using Panchovix's version of [Forge](https://github.com/Panchovix/stable-diffusion-webui-reForge).
> 
> I am having the same issue too. I am already using nihedon's fork but I'm still getting the error message. Sorry I know nothing about this and I'm not even sure if I'm using the right terminologies.

I have not tried reForge yet. But nihedon updated his fork and it is currently working with the updated versions of Forge. No need to switch to older commit.

**Comment by diodiogod** [comment]
> 8e4a6fc

But just so you know, you need to just use git to go back to an older commit. Inside your forge folder, hold "ctrl" + right click. Open powershell. Use git reset --hard <commit-hash>

**Comment by Panchovix** [comment]
By the way, I can confirm it works on reForge after the update to support Forge, so nice!
