### ISSUE TITLE
Documentation of elemental is outdated

### ISSUE THREAD

**Issue by Filexor** [hako-mikan/sd-webui-lora-block-weight#174]
I tried to put lora in prompt like: `<lora:PONY_FD-FrilledBikini:1:IN04-OUT05:ATTNON> ATTNON:.:4`
But I got following error.
```
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001FF88C3EA10>]: ValueError
Traceback (most recent call last):
  File "H:\stable-diffusion-webui-forge\modules\extra_networks.py", line 135, in activate
    extra_network.activate(p, extra_network_args)
  File "H:\stable-diffusion-webui-forge\extensions-builtin\sd_forge_lora\extra_networks_lora.py", line 35, in activate
    unet_multiplier = float(params.positional[2]) if len(params.positional) > 2 else te_multiplier
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'IN04-OUT05'

*** Error running after_extra_networks_activate: H:\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui-forge\modules\scripts.py", line 876, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "H:\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 562, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "H:\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 858, in loradealer
        te,unet = multidealer(te,unet)
                  ^^^^^^^^^^^^^^^^^^^^
      File "H:\stable-diffusion-webui-forge\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 948, in multidealer
        return float(t),float(u)
                        ^^^^^^^^
    ValueError: could not convert string to float: 'IN04-OUT05'

---
```
After checking source code, I found I have to use `lbwe=`.
But it seems not working so I have no clue what to do to make elemental work.

**Comment by hako-mikan** [comment]
Thanks fixed.

**Comment by Filexor** [comment]
I found still there is some documentation issues:
- There is no explanation of syntax for prompt.
- Keys of lora uses diffuser's keys and should be clarified that.
- Description of syntax of "elemental" textbox is not clear enough.
 It should be like: "Identifer:BlockID:Elements:Ratio,BlockID:Elements:Ratio,...,"

**Comment by hako-mikan** [comment]
Added explanation.
https://github.com/hako-mikan/sd-webui-lora-block-weight#elemental
