### ISSUE TITLE
Error running the extension?

### ISSUE THREAD

**Issue by wolfyangfeng** [hako-mikan/sd-webui-lora-block-weight#34]
sorry but after I installed the extension and use it as default setting，it always report error：

Error running process_batch: H:\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "H:\stable-diffusion-webui-directml\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "H:\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 226, in process_batch
    loradealer(self.newprompts ,self.lratios)
AttributeError: 'Script' object has no attribute 'newprompts'

neither I write tags as <lora:virtualgirlAim_v20:0.7:ALL> or <lora:virtualgirlAim_v20:0.7:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1>, it's the same result. 

Please help ,thanks a lot...

**Comment by Kepler-16b** [comment]
Same issue here. Bumping this.

**Comment by LianmingW** [comment]
same issue happening to me.

**Comment by hako-mikan** [comment]
Thanks reporting.
However, I couldn't find the cause.
At any rate, I have changed the code so maybe it will work.

**Comment by LianmingW** [comment]
New error pops up when I updated the code.

                                  Error running process_batch: D:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 228, in process_batch
    loradealer(prompts ,self.lratios)
  File "D:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 399, in loradealer
    calledloras = extra_network_data["lora"]
TypeError: 'NoneType' object is not subscriptable

**Comment by hako-mikan** [comment]
Are you using any extension that modifies the prompt?

**Comment by LianmingW** [comment]
I am using the built in method of running the lora from stable diffusion and I have none of the scripts/extension enabled when I am running the prompt. The installed below extension that is somewhat related to lora, but I don't think it will impact the prompt.
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

**Comment by LianmingW** [comment]
Looks fixed! Thanks for the quick update
