### ISSUE TITLE
[Bug?] List Index out of Range under Certain Conditions

### ISSUE THREAD

**Issue by Zephyr69** [hako-mikan/sd-webui-lora-block-weight#38]
When the lora with block weight preset is not the first lora in the prompt, the following exception is raised:

Error running process_batch: sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 280, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
  File "sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 496, in loradealer
    if len(lorars) > 0: load_loras_blocks(lorans,lorars,multipliers,elements)
  File "sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 535, in load_loras_blocks
    locallora = lbw(locallora,lwei[i],elements[i])
IndexError: list index out of range

**Comment by neavo** [comment]
same problem

**Comment by EvilBT** [comment]
me too

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
