### ISSUE TITLE
Memory Error when running effective Block Analyzer

### ISSUE THREAD

**Issue by Kansaku** [hako-mikan/sd-webui-lora-block-weight#40]
I wanted to try the Effective Block Analyzer function with no luck.
As soon as I press "Generate" the python process eats all my **32GB of RAM**. It stays there a bit and errors out with a Memory Error.
I dont know if this is a normal behavior for this function. So i felt the need to share.

I run a experimental installation of **torch: 2.0.0+cu118** but everything else works as expected.

Console output about the error:

Traceback (most recent call last):
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 595, in newrun    processed = script.run(p, *script_args)
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 312, in run
    zmen = ",".join([str(random.randrange(4294967294)) for x in range(int(ecount))])
  File "H:\Stable-Diffusion-WebUI\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 312, in <listcomp>
    zmen = ",".join([str(random.randrange(4294967294)) for x in range(int(ecount))])
MemoryError

**Comment by hako-mikan** [comment]
Please let me know if it works with the latest version.

**Comment by Kansaku** [comment]
I tested again with the same outcome. Memory runs full and errors out.
Just for clarification: To point the script for the effective block analyzer to the specific lora i do the following:

<lora:ExampleLoraName:0.5:XYZ>

Is this the correct way to do it? Couldnt find anything specific in your documentation.
If i generate with "EBA" enabled and dont put a XYZ flag on a lora. It keeps generating like it should with "EBA", just not changing anything.

Btw, your extension is amazing.

**Comment by hako-mikan** [comment]
Thanks!

Is the value of "number of seed" is 1?

**Comment by Kansaku** [comment]
I put in a Seed Value from a generated Picture. Something like 14157158 for example. The last time i tested i let it stay at the 1 that is configured uppon opening the Plugin.

**Comment by hako-mikan** [comment]
Can you tell us what environment you are using?
