### ISSUE TITLE
I got an error when doing Reload Presets in Elemental

### ISSUE THREAD

**Issue by a-ru2016** [hako-mikan/sd-webui-lora-block-weight#45]
If I do Reload Presets without entering anything additional, I get an error.
The same result occurs when I enter a new preset and click Save Presets, then Reload Presets.
Also, it seems that I have to press Shift+Enter if I want to start a new line in the Elemental preset entry field. Sorry if this is the spec.

何も追加で入力せずにReload Presetsをするとエラーが出ました。
新しいプリセットを入力してSave Presets、Reload Presetsの順番でクリックしても同じ結果です。
また、Elementalのプリセット入力欄で改行をしようと思ったらShift+Enterを押さなければならないようです。仕様なら申し訳ありません。

M1MacbookPro GoogleChrome
python: 3.10.9  •  torch: 2.1.0.dev20230323  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be]

Reload Presetsを押すと出るエラー
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: Script.ui.<locals>.reloadpresets() takes 0 positional arguments but 1 was given

Save Presetsを押すと出るエラー
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
TypeError: Script.ui.<locals>.savepresets() takes 1 positional argument but 2 were given

**Comment by hako-mikan** [comment]
ありがとうございます。
修正しました。ご確認下さい。

**Comment by a-ru2016** [comment]
動作を確認しました。修正いただきありがとうございます。素晴らしいextensionsを作っていただき感謝しております。今後ともよろしくお願いします。
I have confirmed the operation. Thank you for the fix. Thank you for making great extensions. I look forward to working with you in the future.
