### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xincheng233** [hako-mikan/sd-webui-lora-block-weight#46]
No matter how I adjust the position, I will get an error

Error running process_batch: D:\AI\Stable Diffusion\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "D:\AI\Stable Diffusion\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "D:\AI\Stable Diffusion\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 280, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
  File "D:\AI\Stable Diffusion\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 503, in loradealer
    if len(lorars) > 0: load_loras_blocks(lorans,lorars,multipliers,elements,ltype)
  File "D:\AI\Stable Diffusion\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 529, in load_loras_blocks
    lbw(lora.loaded_loras[l],lwei[n],elements[n])
IndexError: list index out of range

**Comment by sashasubbbb** [comment]
Yeah, i've got the same error

> Traceback (most recent call last):
>   File "B:\AIimages\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
>     script.process_batch(p, *script_args, **kwargs)
>   File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 280, in process_batch
>     loradealer(o_prompts ,self.lratios,self.elementals)
>   File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 503, in loradealer
>     if len(lorars) > 0: load_loras_blocks(lorans,lorars,multipliers,elements,ltype)
>   File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 529, in load_loras_blocks
>     lbw(lora.loaded_loras[l],lwei[n],elements[n])
> IndexError: list index out of range

**Comment by bairasky** [comment]
Yes! me too

`Error running process_batch: /stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 280, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
  File "/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 503, in loradealer
    if len(lorars) > 0: load_loras_blocks(lorans,lorars,multipliers,elements,ltype)
  File "/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 529, in load_loras_blocks
    lbw(lora.loaded_loras[l],lwei[n],elements[n])
IndexError: list index out of range`

**Comment by hako-mikan** [comment]
This may be fixed latest update.
If you use latest version, tell me your settings.
Such as other extensions related to LoRAs.

**Comment by jyomu** [comment]
It appears that an error occurs when a LoRa block is not specified.

**Comment by xincheng233** [comment]
> 
I updated the latest version.
I used webui-locon.
However, this bug does not seem to affect the use of lora block weight.

**Comment by hako-mikan** [comment]
Thanks everyone!
I found cause and fixed.

**Comment by nmnmtttt** [comment]
it's work,thank you.
