### ISSUE TITLE
Suggestion: XYZ Plot for img2img

### ISSUE THREAD

**Issue by Fyschunk** [hako-mikan/sd-webui-lora-block-weight#5]
Hello!

Would it be possible to add the XYZ functionality for img2img? It currently doesn't seem to be working, but returns:

```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 177, in process
    lratios["ZYX"] = lzyx
NameError: name 'lzyx' is not defined
```

**Comment by hako-mikan** [comment]
Hello!
This problem has been fixed yesterday's update. Please update and try it out.

**Comment by Fyschunk** [comment]
Hey! 

I have updated the extension, but now I get a different error:

```
Error running process: C:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 178, in process
    loradealer(p,lratios)
  File "C:\stable-diffusion-webui\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 361, in loradealer
    ratios[i] = float(r)
ValueError: could not convert string to float: ''
```
The program will then just generate a single image.

For context, I am trying to run different custom presets for block weights, using settings like this:

![lora_blockmerge](https://user-images.githubusercontent.com/126920872/222858575-ba58cb2b-8071-4b5d-a0f8-a22865a5ee73.jpg)

These settings work fine in txt2img, but in img2img it only creates one picture (and I think it selects only one of the presets for it).

**Comment by hako-mikan** [comment]
Thanks reporting. There was another problem. I fixed so now you can do that.

**Comment by Fyschunk** [comment]
Cool, now it works! Thank you!
