### ISSUE TITLE
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

### ISSUE THREAD

**Issue by southsea9949** [hako-mikan/sd-webui-lora-block-weight#54]
Error calling: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py/ui
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 135, in ui
    bw_ratiotags= gr.TextArea(label="",lines=2,value=ratiostags,visible =True,interactive =True,elem_id="lbw_ratios")
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/templates.py", line 23, in __init__
    super().__init__(lines=7, **kwargs)
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

Error calling: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py/ui
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-lora-block-weight/scripts/lora_block_weight.py", line 135, in ui
    bw_ratiotags= gr.TextArea(label="",lines=2,value=ratiostags,visible =True,interactive =True,elem_id="lbw_ratios")
  File "/root/miniconda3/envs/xl_env/lib/python3.10/site-packages/gradio/templates.py", line 23, in __init__
    super().__init__(lines=7, **kwargs)
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

**Comment by hako-mikan** [comment]
maybe fixed
