### ISSUE TITLE
ValueError: could not convert string to float: '1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1'

### ISSUE THREAD

**Issue by sjwwdz** [hako-mikan/sd-webui-lora-block-weight#55]
when i used this function, it appears  error message below, can any experts help me to solve it?many thanks!
Error running process_batch: E:\novelai-webui-jisanku\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.pyTraceback (most recent call last):
  File "E:\novelai-webui-jisanku\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\novelai-webui-jisanku\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 291, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
  File "E:\novelai-webui-jisanku\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 484, in loradealer
    multiple = float(called.items[1])
ValueError: could not convert string to float: '1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1'

**Comment by sjwwdz** [comment]
Yes, I solved it. This issue was triggered by an operational mistake. when we used this function , we should follow format below,<lora:wxx4-000001:1:NONE>. then it works well.
