### ISSUE TITLE
SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by zffffff** [hako-mikan/sd-webui-lora-block-weight#58]
Error loading script: lora_block_weight.py
Traceback (most recent call last):
  File "D:\sdwebui\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sdwebui\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sdwebui\stable-diffusion-webui\scripts\lora_block_weight.py", line 86
    <title>sd-webui-lora-block-weight/lora_block_weight.py at main · hako-mikan/sd-webui-lora-block-weight</title>
                                                                   ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by hako-mikan** [comment]
Maybe you installed script in wrong way.
Read this [issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2325)
