### ISSUE TITLE
The latest version of SD does not display an interface. Can you update and adapt it?

### ISSUE THREAD

**Issue by wzgrx** [hako-mikan/sd-webui-lora-block-weight#59]
Error loading script: lora_block_weight.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 17, in <module>
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

**Comment by wzgrx** [comment]
> 你使用的是分叉版本吗？也许由我无法测试它修复。所以你试试看。

Tested in the latest version of dve, it works normally. Thank you for the hard work of the developers

**Comment by LaeDev** [comment]
This Error Still occurs in Windows 11. 

`Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 580, in get_font
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 587, in get_font
    return ImageFont.truetype(shared.opts.font or 'javascript/roboto.ttf', fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 619, in newrun
    processed = script.run(p, *script_args)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 448, in run
    grids.append(smakegrid(images,xst,yst,origin,p))
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 569, in smakegrid
    grid = draw_origin(grid, currentmodel,w*len(xs),h*len(ys),w)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 593, in draw_origin
    fnt = get_font(fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 589, in get_font
    return ImageFont.truetype('javascript/roboto.ttf', fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource`
