### ISSUE TITLE
XYZ plot: IN10 is not in list

### ISSUE THREAD

**Issue by aigias** [hako-mikan/sd-webui-lora-block-weight#61]
Hi there,

XYZ plot function. It's a lycoris model, as <lora:name:1:lbw=XYZ>

It listed that changeable blocks : BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11

However when I include IN10 or IN11 in Block ID,  I got the error message in consonle:
Traceback (most recent call last):
  File "E:\SD-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "E:\SD-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\SD-webui\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\SD-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 609, in newrun
    processed = script.run(p, *script_args)
  File "E:\SD-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 416, in run
    if "values" in xtype:c_base = weightsdealer(x,y,base)
  File "E:\SD-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 375, in weightsdealer
    flagger[blockid.index(id)] =changer
ValueError: 'IN10' is not in list

Then I found same issue for following blocks:
IN00,IN03,IN06,IN09,IN10,IN11,OUT00,OUT01,OUT02
----oh...actually the extra blocks of lycoris than lora...

I'm quite sure this is a lycoris model(algo=loha).
And Effective Block Analyzer function works fine for all blocks with the same model.
Did I get anything wrong? Thanks for help in advance.

**Comment by hako-mikan** [comment]
You should add `XYZ:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1` to preset.

**Comment by aigias** [comment]
Problem resolved. Thanks.
