### ISSUE TITLE
error after updating extension

### ISSUE THREAD

**Issue by popsoda27** [hako-mikan/sd-webui-lora-block-weight#64]
Error running process_batch: E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui-directml\modules\scripts.py", line 436, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 294, in process_batch
    loradealer(o_prompts ,self.lratios,self.elementals)
  File "E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 491, in loradealer
    multiple = float(called.items[1])
IndexError: list index out of range

I had just updated this extension and when I tried to generate, this error occured. There wasn't any block weight usage in my prompt.

**Comment by popsoda27** [comment]
version:  •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.29.0

**Comment by hako-mikan** [comment]
Do you still have this problem?
