### ISSUE TITLE
Cannot Display Font

### ISSUE THREAD

**Issue by LaeDev** [hako-mikan/sd-webui-lora-block-weight#66]
Probably Related to #59 Issue. 
Occurs in Windows 11 with highres.fix Option.

```
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 580, in get_font
    from fonts.ttf import Roboto
ModuleNotFoundError: No module named 'fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 587, in get_font
    return ImageFont.truetype(shared.opts.font or 'javascript/roboto.ttf', fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 619, in newrun
    processed = script.run(p, *script_args)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 448, in run
    grids.append(smakegrid(images,xst,yst,origin,p))
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 569, in smakegrid
    grid = draw_origin(grid, currentmodel,w*len(xs),h*len(ys),w)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 593, in draw_origin
    fnt = get_font(fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight-main\scripts\lora_block_weight.py", line 589, in get_font
    return ImageFont.truetype('javascript/roboto.ttf', fontsize)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by hako-mikan** [comment]
May be fixed.
