### ISSUE TITLE
Incompatible with A1111 1.5 extra networks parser

### ISSUE THREAD

**Issue by blooest** [hako-mikan/sd-webui-lora-block-weight#82]
You did update to run your lycodealer so you at least grab lbw= arguments out properly.

Except.. Your parser errors out if the first argument is a nonfloat.
So, you're incompatible with providing the te multiplier as a named argument, or any other purposes one might have for having the te argument being a nonfloat -- the [step weighting control extension](https://github.com/cheald/sd-webui-loractl) comes to mind.

<lora:name:te=1:unet=0.5:lbw=INALL> should be, and is, perfectly valid syntax.
```
*** Error running process_batch: F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 519, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 306, in process_batch
        loradealer(self, o_prompts ,self.lratios,self.elementals)
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 541, in loradealer
        multiple = float(called.items[1])
    ValueError: could not convert string to float: 'te=1'
```

I know this means a pretty major rewrite of your code, but you should use the new [built-in parser](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/Lora/extra_networks_lora.py)'s system for parameters instead of parsing your own like this.

**Comment by hako-mikan** [comment]
Fixed.

**Comment by blooest** [comment]
It still errors out if the te value is provided as a named argument but unet is not provided. This is still valid syntax, as unet will fallback to the te value if not provided.
<lora:name:te=1:lbw=ALL>
```
*** Error running after_extra_networks_activate: F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 535, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 317, in after_extra_networks_activate
        loradealer(self, kwargs["prompts"] ,self.lratios,self.elementals,kwargs["extra_network_data"])
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 538, in loradealer
        multiple = float(syntaxdealer(called.items,"unet=",1))
    ValueError: could not convert string to float: 'te=1'

---
*** Error running process_batch: F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 543, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 306, in process_batch
        loradealer(self, o_prompts ,self.lratios,self.elementals)
      File "F:\Miscellaneous\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py", line 538, in loradealer
        multiple = float(syntaxdealer(called.items,"unet=",1))
    ValueError: could not convert string to float: 'te=1'
```

If it helps, the network class has a unet_multiplier property -- network.Network.unet_multiplier --, if you could read that at runtime instead of trying to parse it out of the prompt again for yourself, it might be a better way.

**Comment by hako-mikan** [comment]
I did not assume the case where only te is specified and unet is not specified.
Now fixed. If unet is not specified, use te.
